TWILIO_AUTH_TOKEN = "PASTE YOUR TWILIO AUTH TOKEN"
TWILIO_SID = "PASTE YOUR TWILIO SID"
TWILIO_PHONE_NUMBER = "PASTE YOUR TWILIO PHONE NUMBER"
EMERGENCY_CONTACT = "PASTE YOUR EMERGENCY CONTACT NUMBER"
